export const GET_PRODUCT_LIST = "app/Services/GET_PRODUCT_LIST";
export const GET_PRODUCT_LIST_SUCCESS = "app/Services/GET_PRODUCT_LIST_SUCCESS";
export const GET_PRODUCT_LIST_FAILURE = "app/Services/GET_PRODUCT_LIST_FAILURE";

export const GET_SERVICE_RESULT = "app/Services/GET_SERVICE_RESULT";
export const GET_SERVICE_RESULT_SUCCESS = "app/Services/GET_SERVICE_RESULT_SUCCESS";
export const GET_SERVICE_RESULT_FAILURE = "app/Services/GET_SERVICE_RESULT_FAILURE";

export const GET_POPULAR_SERVICES = "app/Services/GET_POPULAR_SERVICES";
export const GET_POPULAR_SERVICES_SUCCESS = "app/Services/GET_POPULAR_SERVICES_SUCCESS";
export const GET_POPULAR_SERVICES_FAILURE = "app/Services/GET_POPULAR_SERVICES_FAILURE";
