// OPEN ADD MODAL
export const ORDER_OPEN_ADD_MODAL = "app/Orders/ORDER_OPEN_ADD_MODAL";
export const ORDER_CLOSE_ADD_MODAL = "app/Orders/ORDER_CLOSE_ADD_MODAL";

// OPEN VIEW MODAL
export const ORDER_VIEW_OPEN_MODAL = "app/Orders/ORDER_VIEW_OPEN_MODAL";
export const ORDER_VIEW_CLOSE_MODAL = "app/Orders/ORDER_VIEW_CLOSE_MODAL";

// CUSTOMER CREATE MODAL
export const CUSTOMER_CREATE_OPEN_MODAL =
  "app/Orders/CUSTOMER_CREATE_OPEN_MODAL";
export const CUSTOMER_CREATE_CLOSE_MODAL =
  "app/Orders/CUSTOMER_CREATE_CLOSE_MODAL";

// OPEN DELETE MODAL
export const ORDER_OPEN_DELETE_MODAL = "app/Orders/ORDER_OPEN_DELETE_MODAL";
export const ORDER_CLOSE_DELETE_MODAL = "app/Orders/ORDER_CLOSE_DELETE_MODAL";

// PRODUCT QA MODAL
export const OPEN_ORDER_PRODUCT_QA_MODAL =
  "app/Orders/OPEN_ORDER_PRODUCT_QA_MODAL";
export const CLOSE_ORDER_PRODUCT_QA_MODAL =
  "app/Orders/CLOSE_ORDER_PRODUCT_QA_MODAL";

// GET ALL ORDER
export const GET_ORDER_LIST_REQUEST = "app/Orders/GET_ORDER_LIST_REQUEST";
export const GET_ORDER_LIST_SUCCESS = "app/Orders/GET_ORDER_LIST_SUCCESS";
export const GET_ORDER_LIST_FAILURE = "app/Orders/GET_ORDER_LIST_FAILURE";

// GET CURRENT ORDER
export const GET_CURRENT_ORDER_REQUEST = "app/Orders/GET_CURRENT_ORDER_REQUEST";
export const GET_CURRENT_ORDER_SUCCESS = "app/Orders/GET_CURRENT_ORDER_SUCCESS";
export const GET_CURRENT_ORDER_FAILURE = "app/Orders/GET_CURRENT_ORDER_FAILURE";

// ADD ORDER
export const ADD_ORDER_REQUEST = "app/Orders/ADD_ORDER_REQUEST";
export const ADD_ORDER_SUCCESS = "app/Orders/ADD_ORDER_SUCCESS";
export const ADD_ORDER_FAILURE = "app/Orders/ADD_ORDER_FAILURE";

// EDIT ORDER
export const EDIT_ORDER_REQUEST = "app/Orders/EDIT_ORDER_REQUEST";
export const EDIT_ORDER_SUCCESS = "app/Orders/EDIT_ORDER_SUCCESS";
export const EDIT_ORDER_FAILURE = "app/Orders/EDIT_ORDER_FAILURE";

// DELETE ORDER
export const DELETE_ORDER_REQUEST = "app/Orders/DELETE_ORDER_REQUEST";
export const DELETE_ORDER_SUCCESS = "app/Orders/DELETE_ORDER_SUCCESS";
export const DELETE_ORDER_FAILURE = "app/Orders/DELETE_ORDER_FAILURE";

// ORDERS ADDITIONAL CONTACTS
export const ORDERS_GET_CONTACTS = "app/Orders/GET_CONTACTS";
export const ORDERS_GET_CONTACTS_SUCCESS = "app/Orders/GET_CONTACTS_SUCCESS";
export const ORDERS_GET_CONTACTS_FAILURE = "app/Orders/GET_CONTACTS_FAILURE";
export const ORDERS_OPEN_CONTACTS_ADD = "app/Orders/OPEN_CONTACTS_ADD";
export const ORDERS_CLOSE_CONTACTS_ADD = "app/Orders/CLOSE_CONTACTS_ADD";
export const ORDERS_OPEN_CONTACTS_EDIT = "app/Orders/OPEN_CONTACTS_EDIT";
export const ORDERS_CLOSE_CONTACTS_EDIT = "app/Orders/CLOSE_CONTACTS_EDIT";
export const ORDERS_ADD_CONTACT = "app/Orders/ADD_CONTACTS";
export const ORDERS_ADD_CONTACT_SUCCESS = "app/Orders/ADD_CONTACT_SUCCESS";
export const ORDERS_ADD_CONTACT_FAILURE = "app/Orders/ADD_CONTACT_FAILURE";
export const ORDERS_DELETE_CONTACT = "app/Orders/DELETE_CONTACT";
export const ORDERS_DELETE_CONTACT_SUCCESS =
  "app/Orders/DELETE_CONTACT_SUCCESS";
export const ORDERS_DELETE_CONTACT_FAILURE =
  "app/Orders/DELETE_CONTACT_FAILURE";
export const ORDERS_SET_EDIT_CONTACT = "app/Orders/SET_EDIT_CONTACT";
export const ORDERS_EDIT_CONTACT = "app/Orders/EDIT_CONTACT";
export const ORDERS_EDIT_CONTACT_SUCCESS = "app/Orders/EDIT_CONTACT_SUCCESS";
export const ORDERS_EDIT_CONTACT_FAILURE = "app/Orders/EDIT_CONTACT_FAILURE";

// OPEN INVOICE ADD MODAL
export const OPEN_ORDER_INVOICE_ADD_MODAL =
  "app/Orders/ORDER_INVOICE_ADD_MODAL";
// OPEN INVOICE EDIT MODAL AND FETCH
export const OPEN_ORDER_INVOICE_EDIT_MODAL =
  "app/Orders/OPEN_ORDER_INVOICE_EDIT_MODAL";
// CLOSE INVOICE MODAL
export const CLOSE_ORDER_INVOICE_MODAL = "app/Orders/CLOSE_ORDER_INVOICE_MODAL";

// INVOICE ADD
export const ORDER_INVOICE_ADD_REQUEST = "app/Orders/ORDER_INVOICE_ADD_REQUEST";
export const ORDER_INVOICE_ADD_SUCCESS = "app/Orders/ORDER_INVOICE_ADD_SUCCESS";
export const ORDER_INVOICE_ADD_FAILURE = "app/Orders/ORDER_INVOICE_ADD_FAILURE";
// INVOICE EDIT
export const ORDER_INVOICE_EDIT_REQUEST =
  "app/Orders/ORDER_INVOICE_EDIT_REQUEST";
export const ORDER_INVOICE_EDIT_SUCCESS =
  "app/Orders/ORDER_INVOICE_EDIT_SUCCESS";
export const ORDER_INVOICE_EDIT_FAILURE =
  "app/Orders/ORDER_INVOICE_EDIT_FAILURE";
// INVOICE DELETE
export const ORDER_INVOICE_DELETE_REQUEST =
  "app/Orders/ORDER_INVOICE_DELETE_REQUEST";
export const ORDER_INVOICE_DELETE_SUCCESS =
  "app/Orders/ORDER_INVOICE_DELETE_SUCCESS";
export const ORDER_INVOICE_DELETE_FAILURE =
  "app/Orders/ORDER_INVOICE_DELETE_FAILURE";
// INVOICE FETCH LIST
export const ORDER_INVOICE_LIST_REQUEST =
  "app/Orders/ORDER_INVOICE_LIST_REQUEST";
export const ORDER_INVOICE_LIST_SUCCESS =
  "app/Orders/ORDER_INVOICE_LIST_SUCCESS";
export const ORDER_INVOICE_LIST_FAILURE =
  "app/Orders/ORDER_INVOICE_LIST_FAILURE";
// FETCH CURRENT INVOICE
export const ORDER_CURRENT_INVOICE_REQUEST =
  "app/Orders/ORDER_CURRENT_INVOICE_REQUEST";
export const ORDER_CURRENT_INVOICE_SUCCESS =
  "app/Orders/ORDER_CURRENT_INVOICE_SUCCESS";
export const ORDER_CURRENT_INVOICE_FAILURE =
  "app/Orders/ORDER_CURRENT_INVOICE_FAILURE";

//COMPLAINTS

// OPEN COMPLAINTS ADD MODAL
export const OPEN_ORDER_COMPLAINT_ADD_MODAL =
  "app/Orders/OPEN_ORDER_COMPLAINT_ADD_MODAL";
// OPEN COMPLAINT EDIT MODAL AND FETCH
export const OPEN_ORDER_COMPLAINT_EDIT_MODAL =
  "app/Orders/OPEN_ORDER_COMPLAINT_EDIT_MODAL";
// CLOSE COMPLAINT MODAL
export const CLOSE_ORDER_COMPLAINT_MODAL =
  "app/Orders/CLOSE_ORDER_COMPLAINT_MODAL";

// COMPLAINT ADD
export const ORDER_COMPLAINT_ADD_REQUEST =
  "app/Orders/ORDER_COMPLAINT_ADD_REQUEST";
export const ORDER_COMPLAINT_ADD_SUCCESS =
  "app/Orders/ORDER_COMPLAINT_ADD_SUCCESS";
export const ORDER_COMPLAINT_ADD_FAILURE =
  "app/Orders/ORDER_COMPLAINT_ADD_FAILURE";
// COMPLAINT EDIT
export const ORDER_COMPLAINT_EDIT_REQUEST =
  "app/Orders/ORDER_COMPLAINT_EDIT_REQUEST";
export const ORDER_COMPLAINT_EDIT_SUCCESS =
  "app/Orders/ORDER_COMPLAINT_EDIT_SUCCESS";
export const ORDER_COMPLAINT_EDIT_FAILURE =
  "app/Orders/ORDER_COMPLAINT_EDIT_FAILURE";
// COMPLAINT DELETE
export const ORDER_COMPLAINT_DELETE_REQUEST =
  "app/Orders/ORDER_COMPLAINT_DELETE_REQUEST";
export const ORDER_COMPLAINT_DELETE_SUCCESS =
  "app/Orders/ORDER_COMPLAINT_DELETE_SUCCESS";
export const ORDER_COMPLAINT_DELETE_FAILURE =
  "app/Orders/ORDER_COMPLAINT_DELETE_FAILURE";
// COMPLAINT FETCH LIST
export const ORDER_COMPLAINT_LIST_REQUEST =
  "app/Orders/ORDER_COMPLAINT_LIST_REQUEST";
export const ORDER_COMPLAINT_LIST_SUCCESS =
  "app/Orders/ORDER_COMPLAINT_LIST_SUCCESS";
export const ORDER_COMPLAINT_LIST_FAILURE =
  "app/Orders/ORDER_COMPLAINT_LIST_FAILURE";
// FETCH CURRENT COMPLAINT
export const ORDER_CURRENT_COMPLAINT_REQUEST =
  "app/Orders/ORDER_CURRENT_COMPLAINT_REQUEST";
export const ORDER_CURRENT_COMPLAINT_SUCCESS =
  "app/Orders/ORDER_CURRENT_COMPLAINT_SUCCESS";
export const ORDER_CURRENT_COMPLAINT_FAILURE =
  "app/Orders/ORDER_CURRENT_COMPLAINT_FAILURE";

// FILTER DATA

// CUSTOMERS
export const CUSTOMERS_START_LISTING = "app/Orders/START_LISTING";
export const CUSTOMERS_SET_LISTING = "app/Orders/SET_LISTING";
// CATEGORIES
export const GET_CATEGORIES = "app/Orders/GET_CATEGORIES";
export const GET_CATEGORIES_SUCCESS = "app/Orders/GET_CATEGORIES_SUCCESS";
export const GET_CATEGORIES_FAILURE = "app/Orders/GET_CATEGORIES_FAILURE";

export const GET_FILTER_DATA = "app/Orders/GET_FILTER_DATA";
export const GET_FILTER_DATA_SUCCESS = "app/Orders/GET_FILTER_DATA_SUCCESS";
export const GET_FILTER_DATA_FAILURE = "app/Orders/GET_FILTER_DATA_FAILURE";

// OPEN MODAL
export const OPEN_ORDERS_ADD_MODAL = "app/Orders/OPEN_ORDERS_ADD_MODAL";
export const CLOSE_ORDERS_ADD_MODAL = "app/Orders/CLOSE_ORDERS_ADD_MODAL";

export const OPEN_ORDERS_EDIT_MODAL = "app/Orders/OPEN_ORDERS_EDIT_MODAL";
export const CLOSE_ORDERS_EDIT_MODAL = "app/Orders/CLOSE_ORDERS_EDIT_MODAL";

// ADD RESCHEDULE MODAL
export const ADD_RESCHEDULE_REQUEST = "app/Orders/ADD_RESCHEDULE_REQUEST";
export const ADD_RESCHEDULE_SUCCESS = "app/Orders/ADD_RESCHEDULE_SUCCESS";
export const ADD_RESCHEDULE_FAILURE = "app/Orders/ADD_RESCHEDULE_FAILURE";
