export const SUBMIT_TRADER_FORM = "SUBMIT_TRADER_FORM";
export const SUBMIT_TRADER_FORM_SUCCESS = "SUBMIT_TRADER_FORM_SUCCESS";
export const SUBMIT_TRADER_FORM_FAILURE = "SUBMIT_TRADER_FORM_FAILURE";


export const RESET_TRADER_FORM = "RESET_TRADER_FORM";
