export const CUSTOMERS_CLEANUP = 'app/Customers/CLEANUP';

export const CUSTOMERS_START_LISTING = 'app/Customers/START_LISTING';
export const CUSTOMERS_SET_LISTING = 'app/Customers/SET_LISTING';
export const CUSTOMERS_VIEW_MODAL_OPEN_AND_FETCH =
  'app/Customers/VIEW_MODAL_OPEN_AND_FETCH';
export const CUSTOMERS_CLOSE_VIEW_MODAL = 'app/Customers/CLOSE_VIEW_MODAL';
export const CUSTOMERS_SET_DATEFILTER = 'app/Customers/SET_DATEFILTER';

// CUSTOMERS DELETE
export const CUSTOMERS_DELETE_SUBMIT = 'app/Customers/DELETE_SUBMIT';
export const CUSTOMERS_DELETE_SUBMIT_SUCCESS =
  'app/Customers/DELETE_SUBMIT_SUCCESS';
export const CUSTOMERS_DELETE_SUBMIT_FAILURE =
  'app/Customers/DELETE_SUBMIT_FAILURE';
export const CUSTOMERS_OPEN_DELETE_MODAL = 'app/Customers/OPEN_DELETE_MODAL';
export const CUSTOMERS_CLOSE_DELETE_MODAL = 'app/Customers/CLOSE_DELETE_MODAL';

// CUSTOMERS EDIT
export const CUSTOMERS_EDIT_MODAL_OPEN_AND_FETCH =
  'app/Customers/EDIT_MODAL_OPEN_AND_FETCH';
export const CUSTOMERS_EDIT_MODAL_SUBMIT = 'app/Customers/EDIT_MODAL_SUBMIT';
export const CUSTOMERS_CLOSE_EDIT_MODAL = 'app/Customers/CLOSE_EDIT_MODAL';

export const CUSTOMERS_MODAL_SET_CUSTOMER = 'app/Customers/MODAL_SET_CUSTOMER';
export const CUSTOMERS_MODAL_SUBMIT_SUCCESS =
  'app/Customers/MODAL_SUBMIT_SUCCESS';
export const CUSTOMERS_MODAL_SUBMIT_FAILURE =
  'app/Customers/MODAL_SUBMIT_FAILURE';

export const CUSTOMERS_SET_FILTER_QUERY = 'app/Customers/SET_QUERY_FILTER';
export const CUSTOMERS_CLEAR_FILTERS = 'app/Customers/CLEAR_FILTERS';

export const CUSTOMERS_GET_COMPANIES = `app/Customers/GET_COMPANIES`;
export const CUSTOMERS_SET_COMPANIES = `app/Customers/SET_COMPANIES`;

export const CUSTOMERS_START_ADDRESS_LIST =
  'app/Customers/CUSTOMERS_START_ADDRESS_LIST';
export const CUSTOMERS_SET_ADDRESS_LIST =
  'app/Customers/CUSTOMERS_SET_ADDRESS_LIST';
export const CUSTOMERS_ADDRESS_LIST_SUCCESS =
  'app/Customers/CUSTOMERS_ADDRESS_LIST_SUCCESS';
export const CUSTOMERS_ADDRESS_LIST_FAILURE =
  'app/Customers/CUSTOMERS_ADDRESS_LIST_FAILURE';

// CUSTOMER ADDRESS VIEW / OPEN MODEL

export const CUSTOMERS_ADDRESS_VIEW_MODAL_OPEN_AND_FETCH =
  'app/Customers/CUSTOMERS_ADDRESS_VIEW_MODAL_OPEN_AND_FETCH';
export const CUSTOMERS_ADDRESS_CLOSE_VIEW_MODAL =
  'app/Customers/CUSTOMERS_ADDRESS_CLOSE_VIEW_MODAL';

// CUSTOMERS Address delete
export const CUSTOMERS_ADDRESS_DELETE_SUBMIT =
  'app/Customers/CUSTOMERS_ADDRESS_DELETE_SUBMIT';
export const CUSTOMERS_ADDRESS_DELETE_SUBMIT_SUCCESS =
  'app/Customers/CUSTOMERS_ADDRESS_DELETE_SUBMIT_SUCCESS';
export const CUSTOMERS_ADDRESS_DELETE_SUBMIT_FAILURE =
  'app/Customers/CUSTOMERS_ADDRESS_DELETE_SUBMIT_FAILURE';
export const CUSTOMERS_ADDRESS_OPEN_DELETE_MODAL =
  'app/Customers/CUSTOMERS_ADDRESS_OPEN_DELETE_MODAL';
export const CUSTOMERS_ADDRESS_CLOSE_DELETE_MODAL =
  'app/Customers/CUSTOMERS_ADDRESS_CLOSE_DELETE_MODAL';

// CUSTOMER ADDRESS EDIT
export const CUSTOMERS_ADDRESS_EDIT_MODAL_OPEN_AND_FETCH =
  'app/Customers/CUSTOMERS_ADDRESS_EDIT_MODAL_OPEN_AND_FETCH';
export const CUSTOMERS_ADDRESS_EDIT_MODAL_SUBMIT =
  'app/Customers/CUSTOMERS_ADDRESS_EDIT_MODAL_SUBMIT';
export const CUSTOMERS_ADDRESS_CLOSE_EDIT_MODAL =
  'app/Customers/CUSTOMERS_ADDRESS_CLOSE_EDIT_MODAL';

export const CUSTOMERS_ADDRESS_MODAL_SET_CUSTOMER =
  'app/Customers/CUSTOMERS_ADDRESS_MODAL_SET_CUSTOMER';
export const CUSTOMERS_ADDRESS_MODAL_SUBMIT_SUCCESS =
  'app/Customers/CUSTOMERS_ADDRESS_MODAL_SUBMIT_SUCCESS';
export const CUSTOMERS_ADDRESS_MODAL_SUBMIT_FAILURE =
  'app/Customers/CUSTOMERS_ADDRESS_MODAL_SUBMIT_FAILURE';

export const CUSTOMERS_ADD_MODAL_SUBMIT =
  'app/Customers/CUSTOMERS_ADD_MODAL_SUBMIT';
export const CUSTOMERS_ADD_MODAL_SUBMIT_SUCCESS =
  'app/Customers/CUSTOMERS_ADD_MODAL_SUBMIT_SUCCESS';
export const CUSTOMERS_ADD_MODAL_SUBMIT_FAILURE =
  'app/Customers/CUSTOMERS_ADD_MODAL_SUBMIT_FAILURE';

export const CUSTOMERS_ADDRESS_OPEN_ADD_MODAL =
  'app/Customers/CUSTOMERS_ADDRESS_OPEN_ADD_MODAL';
export const CUSTOMERS_ADDRESS_CLOSE_ADD_MODAL =
  'app/Customers/CUSTOMERS_ADDRESS_CLOSE_ADD_MODAL';

export const CUSTOMERS_ADDRESS_MODAL_ADD =
  'app/Customers/CUSTOMERS_ADDRESS_MODAL_ADD';

export const CUSTOMERS_ADDRESS_MODAL_EDIT_SUBMIT_SUCCESS =
  'app/Customers/CUSTOMERS_ADDRESS_MODAL_EDIT_SUBMIT_SUCCESS';
export const CUSTOMERS_ADDRESS_MODAL_EDIT_SUBMIT_FAILURE =
  'app/Customers/CUSTOMERS_ADDRESS_MODAL_EDIT_SUBMIT_FAILURE';
// ADDITIONAL ADDITIONAL CONTACTS
export const ADDITIONAL_GET_CONTACTS = 'app/Customers/GET_CONTACTS';
export const ADDITIONAL_GET_CONTACTS_SUCCESS =
  'app/Customers/GET_CONTACTS_SUCCESS';
export const ADDITIONAL_GET_CONTACTS_FAILURE =
  'app/Customers/GET_CONTACTS_FAILURE';
export const ADDITIONAL_OPEN_CONTACTS_ADD = 'app/Customers/OPEN_CONTACTS_ADD';
export const ADDITIONAL_CLOSE_CONTACTS_ADD = 'app/Customers/CLOSE_CONTACTS_ADD';
export const ADDITIONAL_OPEN_CONTACTS_EDIT = 'app/Customers/OPEN_CONTACTS_EDIT';
export const ADDITIONAL_CLOSE_CONTACTS_EDIT =
  'app/Customers/CLOSE_CONTACTS_EDIT';
export const ADDITIONAL_ADD_CONTACT = 'app/Customers/ADD_CONTACTS';
export const ADDITIONAL_ADD_CONTACT_SUCCESS =
  'app/Customers/ADD_CONTACT_SUCCESS';
export const ADDITIONAL_ADD_CONTACT_FAILURE =
  'app/Customers/ADD_CONTACT_FAILURE';
export const ADDITIONAL_DELETE_CONTACT = 'app/Customers/DELETE_CONTACT';
export const ADDITIONAL_DELETE_CONTACT_SUCCESS =
  'app/Customers/DELETE_CONTACT_SUCCESS';
export const ADDITIONAL_DELETE_CONTACT_FAILURE =
  'app/Customers/DELETE_CONTACT_FAILURE';
export const ADDITIONAL_SET_EDIT_CONTACT = 'app/Customers/SET_EDIT_CONTACT';
export const ADDITIONAL_EDIT_CONTACT = 'app/Customers/EDIT_CONTACT';
export const ADDITIONAL_EDIT_CONTACT_SUCCESS =
  'app/Customers/EDIT_CONTACT_SUCCESS';
export const ADDITIONAL_EDIT_CONTACT_FAILURE =
  'app/Customers/EDIT_CONTACT_FAILURE';
