//PRODUCT FILE UPLOAD
export const UPLOAD_PRODUCT_FILE_REQUEST ='app/Files/UPLOAD_PRODUCT_FILE_REQUEST';
export const UPLOAD_PRODUCT_FILE_SUCCESS ='app/Files/UPLOAD_PRODUCT_FILE_SUCCESS';
export const UPLOAD_PRODUCT_FILE_FAILURE ='app/Files/UPLOAD_PRODUCT_FILE_FAILURE';