// GET ALL ORDER
export const GET_PRODUCT_DETAILS_REQUEST =
  'app/ProductDetails/GET_PRODUCT_DETAILS_REQUEST'
export const GET_PRODUCT_DETAILS_SUCCESS =
  'app/ProductDetails/GET_PRODUCT_DETAILS_SUCCESS'
export const GET_PRODUCT_DETAILS_FAILURE =
  'app/ProductDetails/GET_PRODUCT_DETAILS_FAILURE'

// GET ALL ORDER
export const GET_PRODUCT_QA_REQUEST =
  'app/ProductDetails/GET_PRODUCT_QA_REQUEST'
export const GET_PRODUCT_QA_SUCCESS =
  'app/ProductDetails/GET_PRODUCT_QA_SUCCESS'
export const GET_PRODUCT_QA_FAILURE =
  'app/ProductDetails/GET_PRODUCT_QA_FAILURE'
export const RESET_PRODUCT_QA =
  'app/ProductDetails/RESET_PRODUCT_QA'

// GET PRODUCT OFFERING
export const GET_PRODUCT_OFFERING_REQUEST =
  'app/ProductDetails/GET_PRODUCT_OFFERING_REQUEST'
export const GET_PRODUCT_OFFERING_SUCCESS =
  'app/ProductDetails/GET_PRODUCT_OFFERING_SUCCESS'
export const GET_PRODUCT_OFFERING_FAILURE =
  'app/ProductDetails/GET_PRODUCT_OFFERING_FAILURE'

//PACKAGE BUILDER
export const GET_PACKAGE_BUILDER_REQUEST =
  'app/ProductDetails/GET_PACKAGE_BUILDER_REQUEST'
export const GET_PACKAGE_BUILDER_SUCCESS =
  'app/ProductDetails/GET_PACKAGE_BUILDER_SUCCESS'
export const GET_PACKAGE_BUILDER_FAILURE =
  'app/ProductDetails/GET_PACKAGE_BUILDER_FAILURE'

// GET PRODUCT OFFER DETAIL
export const GET_PRODUCT_OFFER_DETAIL_REQUEST =
  'app/ProductDetails/GET_PRODUCT_OFFER_DETAIL_REQUEST'
export const GET_PRODUCT_OFFER_DETAIL_SUCCESS =
  'app/ProductDetails/GET_PRODUCT_OFFER_DETAIL_SUCCESS'
export const GET_PRODUCT_OFFER_DETAIL_FAILURE =
  'app/ProductDetails/GET_PRODUCT_OFFER_DETAIL_FAILURE'
