export const UPDATE_USER_PROFILE = "app/Users/UPDATE_USER_PROFILE";
export const UPDATE_USER_PROFILE_PENDING =
  "app/Users/UPDATE_USER_PROFILE_PENDING";
export const UPDATE_USER_PROFILE_SUCCESS =
  "app/Users/UPDATE_USER_PROFILE_SUCCESS";
export const UPDATE_USER_PROFILE_FAILURE =
  "app/Users/UPDATE_USER_PROFILE_FAILURE";
