// GET ALL ORDER
export const GET_CATEGORY_DETAILS_REQUEST = "app/CategoryDetails/GET_CATEGORY_DETAILS_REQUEST";
export const GET_CATEGORY_DETAILS_SUCCESS = "app/CategoryDetails/GET_CATEGORY_DETAILS_SUCCESS";
export const GET_CATEGORY_DETAILS_FAILURE = "app/CategoryDetails/GET_CATEGORY_DETAILS_FAILURE";

// GET ALL ORDER
export const SEARCH_REQUEST = "app/CategoryDetails/SEARCH_REQUEST";
export const SEARCH_REQUEST_SUCCESS = "app/CategoryDetails/SEARCH_REQUEST_SUCCESS";
export const SEARCH_REQUEST_FAILURE = "app/CategoryDetails/SEARCH_REQUEST_FAILURE";


// GET ALL ORDER
export const CUSTOMER_REQUEST = "app/CategoryDetails/CUSTOMER_REQUEST";
export const CUSTOMER_REQUEST_SUCCESS = "app/CategoryDetails/CUSTOMER_REQUEST_SUCCESS";
export const CUSTOMER_REQUEST_FAILURE = "app/CategoryDetails/CUSTOMER_REQUEST_FAILURE";