/*
 * AppConstants
 * Each action has a corresponding type, which the reducer knows and picks up on.
 * To avoid weird typos between the reducer and the actions, we save them as
 * constants here. We prefix them with 'yourproject/YourComponent' so we avoid
 * reducers accidentally picking up actions they shouldn't.
 *
 * Follow this format:
 * export const YOUR_ACTION_CONSTANT = 'yourproject/YourContainer/YOUR_ACTION_CONSTANT';
 */

export const CONTRACTOR_REGISTER_SAGA = 'CONTRACTOR_REGISTER_SAGA'
export const CONTRACTOR_LOGIN = 'CONTRACTOR_LOGIN'
export const CONTRACTOR_LOGIN_SUCCESS = 'CONTRACTOR_LOGIN_SUCCESS'
export const CONTRACTOR_LOGIN_FAILURE = 'CONTRACTOR_LOGIN_FAILURE'

export const CONTRACTOR_CHECK = 'CONTRACTOR_CHECK'
export const CONTRACTOR_CHECK_SUCCESS = 'CONTRACTOR_CHECK_SUCCESS'
export const CONTRACTOR_CHECK_FAILURE = 'CONTRACTOR_CHECK_FAILURE'

export const CONTRACTOR_LOGOUT = 'CONTRACTOR_LOGOUT'
export const CONTRACTOR_LOGOUT_SUCCESS = 'CONTRACTOR_LOGOUT_SUCCESS'
export const CONTRACTOR_LOGOUT_FAILURE = 'CONTRACTOR_LOGOUT_FAILURE'

export const CONTRACTOR_SENT_RESET_PASSWORD = 'CONTRACTOR_SENT_RESET_PASSWORD'
export const CONTRACTOR_SENT_RESET_PASSWORD_SUCCESS =
  'CONTRACTOR_SENT_RESET_PASSWORD_SUCCESS'
export const CONTRACTOR_SENT_RESET_PASSWORD_FAILURE =
  'CONTRACTOR_SENT_RESET_PASSWORD_FAILURE'
export const CONTRACTOR_SENT_RESET_PASSWORD_PENDING =
  'CONTRACTOR_SENT_RESET_PASSWORD_PENDING'
export const ACCOUNT_ACTIVATE = 'app/ACCOUNT_ACTIVATE'
export const ACCOUNT_ACTIVATE_SUCCESS = 'app/ACCOUNT_ACTIVATE_SUCCESS'
export const ACCOUNT_ACTIVATE_FAILURE = 'app/ACCOUNT_ACTIVATE_FAILURE'

export const UPDATE_PASSWORD = 'app/UPDATE_PASSWORD'
export const UDPATE_PASSWORD_SUCCESS = 'app/UPDATE_PASSWORD_SUCCESS'
export const UPDATE_PASSWORD_FAILURE = 'app/UPDATE_PASSWORD_FAILURE'
export const RESET_UPDATE_PASSWORD = 'app/RESET_UPDATE_PASSWORD'

export const ACTIVATE_USER = 'app/ACTIVATE_USER'
export const ACTIVATE_USER_SUCCESS = 'app/ACTIVATE_USER_SUCCESS'
export const ACTIVATE_USER_FAILURE = 'app/ACTIVATE_USER_FAILURE'

// customer login
export const CUSTOMER_SIGNUP = 'CUSTOMER_SIGNUP'
export const CUSTOMER_SIGNUP_SUCCESS = 'CUSTOMER_SIGNUP_SUCCESS'
export const CUSTOMER_SIGNUP_FAILURE = 'CUSTOMER_SIGNUP_FAILURE'

// customer login
export const CUSTOMER_LOGIN = 'CUSTOMER_LOGIN'
export const CUSTOMER_LOGIN_SUCCESS = 'CUSTOMER_LOGIN_SUCCESS'
export const CUSTOMER_LOGIN_FAILURE = 'CUSTOMER_LOGIN_FAILURE'

// customer forgot password
export const CUSTOMER_FORGOT_PASSWORD = 'CUSTOMER_FORGOT_PASSWORD'
export const CUSTOMER_FORGOT_PASSWORD_SUCCESS =
  'CUSTOMER_FORGOT_PASSWORD_SUCCESS'
export const CUSTOMER_FORGOT_PASSWORD_FAILURE =
  'CUSTOMER_FORGOT_PASSWORD_FAILURE'

// customer reset password
export const CUSTOMER_RESET_PASSWORD = 'CUSTOMER_RESET_PASSWORD'
export const CUSTOMER_RESET_PASSWORD_SUCCESS = 'CUSTOMER_RESET_PASSWORD_SUCCESS'
export const CUSTOMER_RESET_PASSWORD_FAILURE = 'CUSTOMER_RESET_PASSWORD_FAILURE'

export const UPDATE_CUSTOMER_USER_PROFILE =
  'app/User/UPDATE_CUSTOMER_USER_PROFILE'
export const UPDATE_CUSTOMER_USER_PROFILE_PENDING =
  'app/User/UPDATE_CUSTOMER_USER_PROFILE_PENDING'
export const UPDATE_CUSTOMER_USER_PROFILE_SUCCESS =
  'app/User/UPDATE_CUSTOMER_USER_PROFILE_SUCCESS'
export const UPDATE_CUSTOMER_USER_PROFILE_FAILURE =
  'app/User/UPDATE_CUSTOMER_USER_PROFILE_FAILURE'

export const CHANGE_PASSWORD = 'app/Auth/CHANGE_PASSWORD'
export const CHANGE_PASSWORD_SUCCESS = 'app/Auth/CHANGE_PASSWORD_SUCCESS'
export const CHANGE_PASSWORD_FAILURE = 'app/Auth/CHANGE_PASSWORD_FAILURE'

export const EMAIL_VERIFY_PASSWORD = 'app/Auth/EMAIL_VERIFY_PASSWORD'
export const EMAIL_VERIFY_PASSWORD_SUCCESS =
  'app/Auth/EMAIL_VERIFY_PASSWORD_SUCCESS'
export const EMAIL_VERIFY_PASSWORD_FAILURE =
  'app/Auth/EMAIL_VERIFY_PASSWORD_FAILURE'

export const GET_PASSWORD_SET = 'app/Auth/GET_PASSWORD_SET'
export const GET_PASSWORD_SET_SUCCESS = 'app/Auth/GET_PASSWORD_SET_SUCCESS'
export const GET_PASSWORD_SET_FAILURE = 'app/Auth/GET_PASSWORD_SET_FAILURE'

export const VERIFY_LINK = 'app/Auth/VERIFY_LINK'
export const VERIFY_LINK_SUCCESS = 'app/Auth/VERIFY_LINK_SUCCESS'
export const VERIFY_LINK_FAILURE = 'app/Auth/VERIFY_LINK_FAILURE'

export const VERIFY_LINK_DATA = 'app/Auth/VERIFY_LINK_DATA'
export const VERIFY_LINK_DATA_SUCCESS = 'app/Auth/VERIFY_LINK_DATA_SUCCESS'
export const VERIFY_LINK_DATA_FAILURE = 'app/Auth/VERIFY_LINK_DATA_FAILURE'

export const GET_TRADER_EMAIL = 'app/Auth/GET_TRADER_EMAIL'
export const GET_TRADER_EMAIL_SUCCESS = 'app/Auth/GET_TRADER_EMAIL_SUCCESS'
export const GET_TRADER_EMAIL_FAILURE = 'app/Auth/GET_TRADER_EMAIL_FAILURE'
