
export const GET_GROUP_DETAILS_REQUEST = "app/groupDetails/GET_GROUP_DETAILS_REQUEST";
export const GET_GROUP_DETAILS_SUCCESS = "app/groupDetails/GET_GROUP_DETAILS_SUCCESS";
export const GET_GROUP_DETAILS_FAILURE = "app/groupDetails/GET_GROUP_DETAILS_FAILURE";

export const GET_GROUP_CATEGORIES_REQUEST = "app/groupDetails/GET_GROUP_CATEGORIES_REQUEST";
export const GET_GROUP_CATEGORIES_SUCCESS = "app/groupDetails/GET_GROUP_CATEGORIES_SUCCESS";
export const GET_GROUP_CATEGORIES_FAILURE = "app/groupDetails/GET_GROUP_CATEGORIES_FAILURE";

// GET CATEGORIES OF LISTING
export const GET_GROUPS_REQUEST = "app/groupDetails/GET_GROUP_REQUEST";
export const GET_GROUPS_SUCCESS = "app/groupDetails/GET_GROUP_SUCCESS";
export const GET_GROUPS_FAILURE = "app/groupDetails/GET_GROUP_FAILURE";

// GET CATEGORIES OF LISTING
export const GET_CATEGORIES_REQUEST = "app/groupDetails/GET_CATEGORIES_REQUEST";
export const GET_CATEGORIES_SUCCESS = "app/groupDetails/GET_CATEGORIES_SUCCESS";
export const GET_CATEGORIES_FAILURE = "app/groupDetails/GET_CATEGORIES_FAILURE";

// GET CATEGORIES OF LISTING
export const GET_PRODUCT_REQUEST = "app/groupDetails/GET_PRODUCT_REQUEST";
export const GET_PRODUCT_SUCCESS = "app/groupDetails/GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_FAILURE = "app/groupDetails/GET_PRODUCT_FAILURE";

// VALIDATE LOCATION
export const VALIDATE_LOCATION_REQUEST = "app/groupDetails/VALIDATE_LOCATION_REQUEST";
export const VALIDATE_LOCATION_SUCCESS = "app/groupDetails/VALIDATE_LOCATION_SUCCESS";
export const VALIDATE_LOCATION_FAILURE = "app/groupDetails/VALIDATE_LOCATION_FAILURE";
export const RESET_VALIDATE_LOCATION = "app/groupDetails/RESET_VALIDATE_LOCATION";


// VALIDATE DIRECT LOCATION
export const VALIDATE_DIRECT_LOCATION_REQUEST = "app/groupDetails/VALIDATE_DIRECT_LOCATION_REQUEST";
export const VALIDATE_DIRECT_LOCATION_SUCCESS = "app/groupDetails/VALIDATE_DIRECT_LOCATION_SUCCESS";
export const VALIDATE_DIRECT_LOCATION_FAILURE = "app/groupDetails/VALIDATE_DIRECT_LOCATION_FAILURE";

// VALIDATE CATEGORY LOCATION
export const VALIDATE_CATEGORY_REQUEST = "app/groupDetails/VALIDATE_CATEGORY_REQUEST";
export const VALIDATE_CATEGORY_SUCCESS = "app/groupDetails/VALIDATE_CATEGORY_SUCCESS";
export const VALIDATE_CATEGORY_FAILURE = "app/groupDetails/VALIDATE_CATEGORY_FAILURE";

// VALIDATE DIRECT LOCATION
export const VALIDATE_CATEGORY_LOCATION = "app/groupDetails/VALIDATE_CATEGORY_LOCATION";
export const VALIDATE_CATEGORY_LOCATION_SUCCESS = "app/groupDetails/VALIDATE_CATEGORY_LOCATION_SUCCESS";
export const VALIDATE_CATEGORY_LOCATION_FAILURE = "app/groupDetails/VALIDATE_CATEGORY_LOCATION_FAILURE";

// VALIDATE CATEGORY LOCATION
export const VALIDATE_PRODUCT_REQUEST = "app/groupDetails/VALIDATE_PRODUCT_REQUEST";
export const VALIDATE_PRODUCT_SUCCESS = "app/groupDetails/VALIDATE_PRODUCT_SUCCESS";
export const VALIDATE_PRODUCT_FAILURE = "app/groupDetails/VALIDATE_PRODUCT_FAILURE";
export const RESET_VALIDATE_PRODUCT = "app/groupDetails/RESET_VALIDATE_PRODUCT";