// GET ALL ORDER
export const ADD_ORDER = 'app/OrderFlow/ADD_ORDER'
export const ADD_ORDER_SUCCESS = 'app/OrderFlow/ADD_ORDER_SUCCESS'
export const ADD_ORDER_FAILURE = 'app/OrderFlow/ADD_ORDER_FAILURE'
export const RESET_ORDER = 'app/OrderFlow/RESET_ORDER'

//PAYMENT
export const CREATE_PAYMENT = 'app/OrderFlow/CREATE_PAYMENT'
export const CREATE_PAYMENT_SUCCESS = 'app/OrderFlow/CREATE_PAYMENT_SUCCESS'
export const CREATE_PAYMENT_FAILURE = 'app/OrderFlow/CREATE_PAYMENT_FAILURE'

// GET ALL ORDER
export const EDIT_VISIT = 'app/OrderFlow/EDIT_VISIT'
export const EDIT_VISIT_SUCCESS = 'app/OrderFlow/EDIT_VISIT_SUCCESS'
export const EDIT_VISIT_FAILURE = 'app/OrderFlow/EDIT_VISIT_FAILURE'

// GET ALL ORDER
export const GET_ORDER_FLOW = 'app/OrderFlow/GET_ORDER_FLOW'
export const GET_ORDER_FLOW_SUCCESS = 'app/OrderFlow/GET_ORDER_FLOW_SUCCESS'
export const GET_ORDER_FLOW_FAILURE = 'app/OrderFlow/GET_ORDER_FLOW_FAILURE'

export const GET_ADDONS = 'app/OrderFlow/GET_ADDONS'
export const GET_ADDONS_SUCCESS = 'app/OrderFlow/GET_ADDONS_SUCCESS'
export const GET_ADDONS_FAILURE = 'app/OrderFlow/GET_ADDONS_FAILURE'

export const OPEN_ORDER_EDIT_MODAL = 'app/OrderFlow/OPEN_ORDER_EDIT_MODAL'
export const CLOSE_ORDER_EDIT_MODAL = 'app/OrderFlow/CLOSE_ORDER_EDIT_MODAL'

export const OPEN_VISIT_EDIT_MODAL = 'app/OrderFlow/OPEN_VISIT_EDIT_MODAL'
export const CLOSE_VISIT_EDIT_MODAL = 'app/OrderFlow/CLOSE_VISIT_EDIT_MODAL'

export const OPEN_QUOTATION_EDIT_MODAL =
  'app/OrderFlow/OPEN_QUOTATION_EDIT_MODAL'
export const CLOSE_QUOTATION_EDIT_MODAL =
  'app/OrderFlow/CLOSE_QUOTATION_EDIT_MODAL'

// GET ALL ORDER
export const DELETE_IMAGE = 'app/OrderFlow/DELETE_IMAGE'
export const DELETE_IMAGE_SUCCESS = 'app/OrderFlow/DELETE_IMAGE_SUCCESS'
export const DELETE_IMAGE_FAILURE = 'app/OrderFlow/DELETE_IMAGE_FAILURE'

export const OPEN_ORDER_PAY_MODAL = 'app/OrderFlow/OPEN_ORDER_PAY_MODAL'
export const CLOSE_ORDER_PAY_MODAL = 'app/OrderFlow/CLOSE_ORDER_PAY_MODAL'

// GET ALL ORDER
export const GET_ORDER_DETAILS = 'app/OrderFlow/GET_ORDER_DETAILS'
export const GET_ORDER_DETAILS_SUCCESS =
  'app/OrderFlow/GET_ORDER_DETAILS_SUCCESS'
export const GET_ORDER_DETAILS_FAILURE =
  'app/OrderFlow/GET_ORDER_DETAILS_FAILURE'

// ADDON
export const OPEN_ADDON_EDIT_MODAL = 'app/OrderFlow/OPEN_ADDON_EDIT_MODAL'
export const CLOSE_ADDON_EDIT_MODAL = 'app/OrderFlow/CLOSE_ADDON_EDIT_MODAL'

// GET ALL ORDER
export const EDIT_ADDON = 'app/OrderFlow/EDIT_ADDON'
export const EDIT_ADDON_SUCCESS = 'app/OrderFlow/EDIT_ADDON_SUCCESS'
export const EDIT_ADDON_FAILURE = 'app/OrderFlow/EDIT_ADDON_FAILURE'

// CHECK MAX JOB
export const CHECK_MAX_JOB = 'app/OrderFlow/CHECK_MAX_JOB'
export const CHECK_MAX_JOB_SUCCESS = 'app/OrderFlow/CHECK_MAX_JOB_SUCCESS'
export const CHECK_MAX_JOB_FAILURE = 'app/OrderFlow/CHECK_MAX_JOB_FAILURE'

export const GET_QUOTEADJUST_DATA = 'app/Visits/GET_QUOTEADJUST_DATA'
export const GET_QUOTEADJUST_DATA_SUCCESS =
  'app/Visits/GET_QUOTEADJUST_DATA_SUCCESS'
export const GET_QUOTEADJUST_DATA_FAILURE =
  'app/Visits/GET_QUOTEADJUST_DATA_FAILURE'
// STORE_QUOTEADJUST_DATA
export const ACCEPT_QUOTEADJUST_DATA = 'app/Visits/ACCEPT_QUOTEADJUST_DATA'
export const ACCEPT_QUOTEADJUST_DATA_SUCCESS =
  'app/Visits/ACCEPT_QUOTEADJUST_DATA_SUCCESS'
export const ACCEPT_QUOTEADJUST_DATA_FAILURE =
  'app/Visits/ACCEPT_QUOTEADJUST_DATA_FAILURE'

// STORE_QUOTEADJUST_DATA
export const REJECT_QUOTEADJUST_DATA = 'app/Visits/REJECT_QUOTEADJUST_DATA'
export const REJECT_QUOTEADJUST_DATA_SUCCESS =
  'app/Visits/REJECT_QUOTEADJUST_DATA_SUCCESS'
export const REJECT_QUOTEADJUST_DATA_FAILURE =
  'app/Visits/REJECT_QUOTEADJUST_DATA_FAILURE'
// STORE_QUOTEADJUST_DATA
export const PAY_QUOTEADJUST = 'app/Visits/PAY_QUOTEADJUST'
export const PAY_QUOTEADJUST_SUCCESS = 'app/Visits/PAY_QUOTEADJUST_SUCCESS'
export const PAY_QUOTEADJUST_FAILURE = 'app/Visits/PAY_QUOTEADJUST_FAILURE'
