export const GET_JOBS = "app/Jobs/GET_JOBS";
export const GET_JOBS_PENDING = "app/Jobs/GET_JOBS_PENDING";
export const GET_JOBS_SUCCESS = "app/Jobs/GET_JOBS_SUCCESS";
export const GET_JOBS_FAILURE = "app/Jobs/GET_JOBS_FAILURE";
export const JOBS_CLEANUP = "app/Jobs/JOBS_CLEANUP";
export const JOBS_SET_DATEFILTER = "app/Jobs/JOBS_SET_DATEFILTER";
export const JOBS_GET_FILTER_DATA = "app/Jobs/JOBS_GET_FILTER_DATA";
export const JOBS_GET_FILTER_DATA_SUCCESS =
  "app/Jobs/JOBS_GET_FILTER_DATA_SUCCESS";
export const JOBS_GET_FILTER_DATA_FAILURE =
  "app/Jobs/JOBS_GET_FILTER_DATA_FAILURE";
export const GET_JOBS_VISITS = "app/Jobs/GET_JOBS_VISITS";
export const GET_JOBS_VISITS_SUCCESS = "app/Jobs/GET_JOBS_VISITS_SUCCESS";
export const GET_JOBS_VISITS_FAILURE = "app/Jobs/GET_JOBS_VISITS_FAILURE";
export const GET_JOBS_VISITS_PENDING = "app/Jobs/GET_JOBS_VISITS_PENDING";
export const GET_JOBS_COSTS = "app/Jobs/GET_JOBS_COSTS";
export const GET_JOBS_COSTS_SUCCESS = "app/Jobs/GET_JOBS_COSTS_SUCCESS";
export const GET_JOBS_COSTS_FAILURE = "app/Jobs/GET_JOBS_COSTS_FAILURE";
export const GET_JOBS_COSTS_PENDING = "app/Jobs/GET_JOBS_COSTS_PENDING";
export const GET_JOBS_TRIAGES = "app/Jobs/GET_JOBS_TRIAGES";
export const GET_JOBS_TRIAGES_SUCCESS = "app/Jobs/GET_JOBS_TRIAGES_SUCCESS";
export const GET_JOBS_TRIAGES_FAILURE = "app/Jobs/GET_JOBS_TRIAGES_FAILURE";
export const GET_JOBS_TRIAGES_PENDING = "app/Jobs/GET_JOBS_TRIAGES_PENDING";
export const JOBS_GET_NOTES = "app/Jobs/JOBS_GET_NOTES";
export const JOBS_GET_NOTES_SUCCESS = "app/Jobs/JOBS_GET_NOTES_SUCCESS";
export const JOBS_GET_NOTES_FAILURE = "app/Jobs/JOBS_GET_NOTES_FAILURE";
export const JOBS_ADD_NOTE = "app/Jobs/JOBS_ADD_NOTES";
export const JOBS_ADD_NOTE_SUCCESS = "app/Jobs/JOBS_ADD_NOTES_SUCCESS";
export const JOBS_ADD_NOTE_FAILURE = "app/Jobs/JOBS_ADD_NOTES_FAILURE";
export const JOBS_DELETE_NOTE = "app/Jobs/JOBS_DELETE_NOTE";
export const JOBS_DELETE_NOTE_SUCCESS = "app/Jobs/JOBS_DELETE_NOTE_SUCCESS";
export const JOBS_DELETE_NOTE_FAILURE = "app/Jobs/JOBS_DELETE_NOTE_FAILURE";
export const JOBS_SET_EDIT_NOTE = "app/Jobs/JOBS_SET_EDIT_NOTE";
export const JOBS_CANCEL_NOTE_EDIT = "app/Jobs/JOBS_CANCEL_NOTE_EDIT";
export const JOBS_EDIT_NOTE = "app/Jobs/JOBS_EDIT_NOTE";
export const JOBS_EDIT_NOTE_SUCCESS = "app/Jobs/JOBS_EDIT_NOTE_SUCCESS";
export const JOBS_EDIT_NOTE_FAILURE = "app/Jobs/JOBS_EDIT_NOTE_FAILURE";
export const JOBS_SAVE_TRIAGE = "app/Jobs/JOBS_SAVE_TRIAGE";
export const JOBS_SAVE_TRIAGE_SUCCESS = "app/Jobs/JOBS_SAVE_TRIAGE_SUCCESS";
export const JOBS_SAVE_TRIAGE_FAILURE = "app/Jobs/JOBS_SAVE_TRIAGE_FAILURE";
export const JOBS_VIEW_OPEN_AND_FETCH = "app/Jobs/JOBS_VIEW_OPEN_AND_FETCH";
export const JOBS_SET_JOB = "app/Jobs/JOBS_SET_JOB";
export const JOBS_EDIT_SUBMIT = "app/Jobs/JOBS_EDIT_SUBMIT";
export const JOBS_EDIT_SUBMIT_SUCCESS = "app/Jobs/JOBS_EDIT_SUBMIT_SUCCESS";
export const JOBS_EDIT_SUBMIT_FAILURE = "app/Jobs/JOBS_EDIT_SUBMIT_FAILURE";

// add visit
export const ADD_JOB_VISIT = "app/Jobs/ADD_JOB_VISIT";
export const ADD_JOB_VISIT_SUCCESS = "app/Jobs/ADD_JOB_VISIT_SUCCESS";
export const ADD_JOB_VISIT_FAILURE = "app/Jobs/ADD_JOB_VISIT_FAILURE";
export const ADD_JOB_VISIT_PENDING = "app/Jobs/ADD_JOB_VISIT_PENDING";
export const GET_VISIT_DETAILS = "app/Jobs/GET_VISIT_DETAILS";

export const OPEN_ADD_VISIT_MODEL = "app/Jobs/OPEN_ADD_VISIT_MODEL";
export const OPEN_ADD_VISIT_MODELS = "app/Jobs/OPEN_ADD_VISIT_MODELS";
export const OPEN_ADD_VISIT_VIEW_MODELS = "app/Jobs/OPEN_ADD_VISIT_VIEW_MODELS";

export const CLOSE_VISIT_MODEL = "app/Jobs/CLOSE_VISIT_MODEL";
export const  CLOSE_VISIT_DETAIL_MODEL = "app/Jobs/CLOSE_VISIT_DETAIL_MODEL";
export const CLOSE_VISIT_VIEW_MODEL= "app/Jobs/CLOSE_VISIT_VIEW_MODEL";


export const OPEN_EDIT_VISIT_MODEL = "app/Jobs/OPEN_EDIT_VISIT_MODEL";
export const REJECT_JOB_VISIT = "app/Jobs/REJECT_JOB_VISIT";

export const VISITS_GET_ENGINEERS = "app/Jobs/GET_ENGINEER";
export const VISITS_SET_ENGINEERS = "app/Jobs/SET_ENGINEER";

export const VISITS_GET_JOB = "app/Jobs/GET_JOB";
export const VISITS_SET_JOB = "app/Jobs/SET_JOB";
export const VISITS_GET_JOB_FAILURE = "app/Jobs/GET_JOB_FAILURE";
export const VISITS_START_LISTING = "app/Jobs/START_LISTING";
export const VISITS_SET_LISTING = "app/Jobs/SET_LISTING";
export const VISITS_GET_LISTING_FAILURE = "app/Jobs/GET_LISTING_FAILURE";
export const VISITS_CLOSE_DELETE_MODAL = "app/Jobs/VISITS_CLOSE_DELETE_MODAL";
export const VISITS_OPEN_DELETE_MODAL = "app/Jobs/VISITS_OPEN_DELETE_MODAL";
export const SET_CURRENT_VISIT = "app/Jobs/SET_CURRENT_VISIT";
export const VISITS_SET_LISTINGS = "app/Jobs/VISITS_SET_LISTINGS";
export const VISITS_START_LISTINGS = "app/Jobs/VISITS_START_LISTINGS";
export const GET_VISIT_DETAIL = "app/Jobs/GET_VISIT_DETAIL";

export const VISITS_START_LIST = "app/Jobs/VISITS_START_LIST";

export const OPEN_VISIT_LISTING_MODEL = "app/Jobs/OPEN_VISIT_LISTING_MODEL";
export const CLOSE_VISIT_LISTING_MODEL = "app/Jobs/CLOSE_VISIT_LISTING_MODEL";
export const OPEN_VIEW_VISIT_DETAIL_MODEL =
  "app/Jobs/OPEN_VIEW_VISIT_DETAIL_MODEL";
export const CLOSE_VIEW_VISIT_DETAIL_MODEL =
  "app/Jobs/CLOSE_VIEW_VISIT_DETAIL_MODEL";
export const OPEN_RESCHEDULE_VISIT_MODEL =
  "app/Jobs/OPEN_RESCHEDULE_VISIT_MODEL";
export const CLOSE_RESCHEDULE_VISIT_MODEL =
  "app/Jobs/CLOSE_RESCHEDULE_VISIT_MODEL";
