export const SUBMIT_PROMOTIONAL_FORM = "SUBMIT_PROMOTIONAL_FORM";
export const SUBMIT_PROMOTIONAL_FORM_SUCCESS = "SUBMIT_PROMOTIONAL_FORM_SUCCESS";
export const SUBMIT_PROMOTIONAL_FORM_FAILURE = "SUBMIT_PROMOTIONAL_FORM_FAILURE";

export const RESET_PROMOTIONAL_FORM = "RESET_PROMOTIONAL_FORM";