// GET ALL ORDER
export const GET_JOB_COMPLETED_REQUEST = "app/Vists/GET_JOB_COMPLETED_REQUEST";
export const GET_JOB_COMPLETED_SUCCESS = "app/Vists/GET_JOB_COMPLETED_SUCCESS";
export const GET_JOB_COMPLETED_FAILURE = "app/Vists/GET_JOB_COMPLETED_FAILURE";
