/*
 *
 * Conractors constants
 *
 */
// Trader admin list
export const TRADER_ADMIN_LIST_FETCH = "app/Trader/TRADER_ADMIN_LIST_FETCH";
export const TRADER_ADMIN_LIST_FETCH_SUCCESS =
  "app/Trader/TRADER_ADMIN_LIST_FETCH_SUCCESS";
export const TRADER_ADMIN_LIST_FETCH_FAILURE =
  "app/Trader/TRADER_ADMIN_LIST_FETCH_FAILURE";

// Fetch Trader admin
export const FETCH_CURRNT_TRADER_ADMIN = "app/Trader/FETCH_CURRNT_TRADER_ADMIN";
export const FETCH_CURRNT_TRADER_ADMIN_SUCCESS =
  "app/Trader/FETCH_CURRNT_TRADER_ADMIN_SUCCESS";
export const FETCH_CURRNT_TRADER_ADMIN_FAILURE =
  "app/Trader/FETCH_CURRNT_TRADER_ADMIN_FAILURE";

// Trader admin Add Modal
export const TRADER_ADMIN_ADD_MODAL_OPEN =
  "app/Trader/TRADER_ADMIN_ADD_MODAL_OPEN";
export const TRADER_ADMIN_ADD_MODAL_CLOSE =
  "app/Trader/TRADER_ADMIN_ADD_MODAL_CLOSE";

// Trader admin Edit Modal
export const TRADER_ADMIN_EDIT_MODAL_OPEN =
  "app/Trader/TRADER_ADMIN_EDIT_MODAL_OPEN";
export const TRADER_ADMIN_EDIT_MODAL_CLOSE =
  "app/Trader/TRADER_ADMIN_EDIT_MODAL_CLOSE";

// Trader admin View Modal
export const TRADER_ADMIN_VIEW_MODAL_OPEN =
  "app/Trader/TRADER_ADMIN_VIEW_MODAL_OPEN";
export const TRADER_ADMIN_VIEW_MODAL_CLOSE =
  "app/Trader/TRADER_ADMIN_VIEW_MODAL_CLOSE";

// CONTRACTORS VIEW
export const TRADER_START_LISTING = "app/Trader/START_LISTING";
export const TRADER_SET_LISTING = "app/Trader/SET_LISTING";

// DELETE
export const TRADERS_OPEN_DELETE_MODAL = "app/Trader/OPEN_DELETE_MODAL";
export const TRADERS_CLOSE_DELETE_MODAL = "app/Trader/CLOSE_DELETE_MODAL";

// ADD
export const TRADERS_ADD_SUBMIT = "app/Trader/ADD_SUBMIT";
export const TRADERS_SUBMIT_SUCCESS = "app/Trader/SUBMIT_SUCCESS";
export const TRADERS_SUBMIT_FAILURE = "app/Trader/SUBMIT_FAILURE";

// ADD TRADER ADMIN
export const ADD_TRADERS_ADMIN_REQUEST = "app/Trader/ADD_TRADERS_ADMIN_REQUEST";
export const ADD_TRADERS_ADMIN_SUCCESS = "app/Trader/ADD_TRADERS_ADMIN_SUCCESS";
export const ADD_TRADERS_ADMIN_FAILURE = "app/Trader/ADD_TRADERS_ADMIN_FAILURE";

// EDIT TRADER ADMIN
export const TRADERS_ADMIN_EDIT_OPEN_AND_FETCH =
  "app/Trader/TRADERS_ADMIN_EDIT_OPEN_AND_FETCH";
export const TRADERS_ADMIN_FETCH_SUCCESS =
  "app/Trader/TRADERS_ADMIN_FETCH_SUCCESS";
export const TRADERS_ADMIN_FETCH_FAILURE =
  "app/Trader/TRADERS_ADMIN_FETCH_FAILURE";

export const TRADERS_ADMIN_EDIT_REQUEST =
  "app/Trader/TRADERS_ADMIN_EDIT_REQUEST";
export const TRADERS_ADMIN_EDIT_SUCCESS =
  "app/Trader/TRADERS_ADMIN_EDIT_SUCCESS";
export const TRADERS_ADMIN_EDIT_FAILURE =
  "app/Trader/TRADERS_ADMIN_EDIT_FAILURE";

// EDIT SUBMIT
export const TRADERS_VIEW_OPEN_AND_FETCH = "app/Trader/VIEW_OPEN_AND_FETCH";
export const TRADERS_EDIT_SUBMIT = "app/Trader/EDIT_SUBMIT";

// DELETE SUBMIT
export const TRADERS_DELETE_SUBMIT = "app/Trader/DELETE_SUBMIT";
export const TRADERS_DELETE_SUBMIT_SUCCESS = "app/Trader/DELETE_SUBMIT_SUCCESS";
export const TRADERS_DELETE_SUBMIT_FAILURE = "app/Trader/DELETE_SUBMIT_FAILURE";

// DELETE TRADER ADMIN SUBMIT
export const TRADERS_ADMIN_DELETE_SUBMIT =
  "app/Trader/TRADERS_ADMIN_DELETE_SUBMIT";
export const TRADERS_ADMIN_DELETE_SUBMIT_SUCCESS =
  "app/Trader/TRADERS_ADMIN_DELETE_SUBMIT_SUCCESS";
export const TRADERS_ADMIN_DELETE_SUBMIT_FAILURE =
  "app/Trader/TRADERS_ADMIN_DELETE_SUBMIT_FAILURE";

export const CONTRACTORS_GET_FILTER_DATA = "app/Contractors/GET_FILTER_DATA";
export const CONTRACTORS_GET_FILTER_DATA_SUCCESS =
  "app/Contractors/GET_FILTER_DATA_SUCCESS";
export const CONTRACTORS_GET_FILTER_DATA_FAILURE =
  "app/Contractors/GET_FILTER_DATA_FAILURE";
export const CONTRACTORS_ADD_POSTCODE = "app/Contractors/ADD_POSTCODE";
export const CONTRACTORS_POSTCODE_SUCCESS = "app/Contractors/POSTCODE_SUCCESS";
export const CONTRACTORS_POSTCODE_FAILURE = "app/Contractors/POSTCODE_FAILURE";
export const CONTRACTORS_POSTCODE_START_LISTING =
  "app/Contractors/POSTCODE_START_LISTING";
export const CONTRACTORS_POSTCODE_SET_LISTING =
  "app/Contractors/POSTCODE_SET_LISTING";
export const CONTRACTORS_DELETE_POSTCODE = "app/Contractors/DELETE_POSTCODE";
export const CONTRACTORS_DELETE_POSTCODE_SUCCESS =
  "app/Contractors/DELETE_POSTCODE_SUCCESS";
export const CONTRACTORS_DELETE_POSTCODE_FAILURE =
  "app/Contractors/DELETE_POSTCODE_FAILURE";
export const CONTRACTORS_SET_DATA = "app/Contractors/SET_DATA";
export const CONTRACTORS_POSTCODE_EDIT = "app/Contractors/POSTCODE_EDIT";

export const CONTRACTORS_SET_JOB = "app/Contractors/SET_JOB";

// constants for document upload
export const CONTRACTORS_DOCUMENT_START_LISTING =
  "app/Contractors/DOCUMENT_START_LISTING";
export const CONTRACTORS_DOCUMENT_SET_LISTING =
  "app/Contractors/DOCUMENT_SET_LISTING";
export const CONTRACTORS_DOCUMENT_SET_FILTER =
  "app/Contractors/DOCUMENT_SET_FILTER_DATA";
export const CONTRACTORS_DOCUMENT_CLEAR_FILTERS =
  "app/Contractors/DOCUMENT_CLEAR_FILTER_DATA";

export const CONTRACTORS_DOCUMENT_SUBMIT = "app/Contractors/DOCUMENT_SUBMIT";
export const CONTRACTORS_DOCUMENT_EDIT_SUBMIT =
  "app/Contractors/DOCUMENT_SUBMIT_EDIT";
export const CONTRACTORS_ADD_DOCUMENT_MODAL_OPEN =
  "app/Contractors/DOCUMENT_UPLOAD_MODAL_OPEN";
export const CONTRACTORS_ADD_DOCUMENT_MODAL_CLOSE =
  "app/Contractors/DOCUMENT_UPLOAD_MODAL_CLOSE";
export const CONTRACTORS_EDIT_DOCUMENT_MODAL_OPEN =
  "app/Contractors/DOCUMENT_EDIT_UPLOAD_MODAL_OPEN";
export const CONTRACTORS_EDIT_DOCUMENT_MODAL_CLOSE =
  "app/Contractors/DOCUMENT_EDIT_UPLOAD_MODAL_CLOSE";
export const CONTRACTORS_DELETE_DOCUMENT_MODAL_OPEN =
  "app/Contractors/DOCUMENT_DELETE_MODAL_OPEN";
export const CONTRACTORS_DELETE_DOCUMENT_MODAL_CLOSE =
  "app/Contractors/DOCUMENT_DELETE_MODAL_CLOSE";

export const CONTRACTORS_DOCUMENT_DELETE = "app/Contractors/DOCUMENT_DELETE";

export const CONTRACTORS_FETCH_SKILLS =
  "app/Contractors/FETCH_CONTRACTORS_SKILLS";
export const CONTRACTORS_FETCH_SKILLS_SUCCESS =
  "app/Contractors/FETCH_CONTRACTORS_SKILLS_SUCCESS";
export const CONTRACTORS_FETCH_SKILLS_FAILURE =
  "app/Contractors/FETCH_CONTRACTORS_SKILLS_FAILURE";

// ADD STAFF
export const TRADERS_STAFF_ADD_SUBMIT = "app/Trader/_STAFF_ADD_SUBMIT";
export const TRADERS_STAFF_SUBMIT_SUCCESS = "app/Trader/_STAFF_SUBMIT_SUCCESS";
export const TRADERS_STAFF_SUBMIT_FAILURE = "app/Trader/_STAFF_SUBMIT_FAILURE";
// GET STAFF
export const TRADER_STAFF_START_LISTING = "app/Trader/STAFF_START_LISTING";
export const TRADER_STAFF_SET_LISTING = "app/Trader/STAFF_SET_LISTING";
// CATEGORY ADD
export const TRADER_CATEGORY_ADD_SUBMIT = "app/Trader/CATEGORY_ADD_SUBMIT";
export const TRADER_CATEGORY_SUBMIT_SUCCESS =
  "app/Trader/CATEGORY_SUBMIT_SUCCESS";
export const TRADER_CATEGORY_SUBMIT_FAILURE =
  "app/Trader/CATEGORY_SUBMIT_FAILURE";
// CATEGORY GET ALL
export const TRADER_CATEGORY_START_LISTING =
  "app/Trader/CATEGORY_START_LISTING";
export const TRADER_CATEGORY_SET_LISTING = "app/Trader/CATEGORY_SET_LISTING";
// TRADER CATEGORY ADD MODAL
export const TRADER_ADD_CATEGORY_MODAL_OPEN =
  "app/Contractors/CATEGORY_ADD_MODAL_OPEN";
export const TRADER_ADD_CATEGORY_MODAL_CLOSE =
  "app/Contractors/CATEGORY_ADD_MODAL_CLOSE";
// CATEGORY EDIT MODAL
export const TRADER_EDIT_CATEGORY_MODAL_OPEN =
  "app/Contractors/CATEGORY_EDIT_MODAL_OPEN";
export const TRADER_EDIT_CATEGORY_MODAL_CLOSE =
  "app/Contractors/CATEGORY_EDIT_MODAL_CLOSE";
// DELETE MODAL
export const TRADER_DELETE_CATEGORY_MODAL_OPEN =
  "app/Contractors/CATEGORY_DELETE_MODAL_OPEN";
export const TRADER_DELETE_CATEGORY_MODAL_CLOSE =
  "app/Contractors/CATEGORY_DELETE_MODAL_CLOSE";
// DELETE SUBMIT
export const TRADER_CATEGORY_DELETE = "app/Trader/SUBMIT_CATEGORY_DELETE";
export const TRADERS_POSTCODE_DELETE_SUBMIT =
  "app/Trader/TRADERS_POSTCODE_DELETE_SUBMIT";
// Trader Post cover Modal
export const TRADER_POST_COVER_MODAL_OPEN =
  "app/Trader/TRADER_POST_COVER_MODAL_OPEN";
export const TRADER_POST_COVER_MODALL_CLOSE =
  "app/Trader/TRADER_POST_COVER_MODALL_CLOSE";

// FETCH ALL CATEGORIES
export const CATEGORY_START_LISTING = "app/Trader/CATEGORIES_START_LISTING";
export const CATEGORY_SET_LISTING = "app/Trader/CATEGORIES_SET_LISTING";
export const CATEGORY_LISTING_ERROR = "app/Trader/CATEGORIES_LISTING_ERROR";

// CATEGORY EDIT
export const TRADER_CATEGORY_EDIT_SUBMIT = "app/Trader/CATEGORY_EDIT_SUBMIT";
export const TRADER_CATEGORY_EDIT_SUBMIT_SUCCESS =
  "app/Trader/CATEGORY_EDIT_SUBMIT_SUCCESS";
export const TRADER_CATEGORY_EDIT_SUBMIT_FAILURE =
  "app/Trader/CATEGORY_EDIT_SUBMIT_FAILURE";

// GET SINGLE STAFF
export const TRADERS_STAFF_VIEW_MODAL_OPEN =
  "app/Trader/TRADERS_STAFF_VIEW_MODAL_OPEN";
export const TRADERS_STAFF_VIEW_MODAL_CLOSE =
  "app/Trader/TRADERS_STAFF_VIEW_MODAL_CLOSE";
export const TRADERS_STAFF_FETCH_SUCCESS =
  "app/Trader/TRADERS_STAFF_FETCH_SUCCESS";
export const TRADERS_STAFF_FETCH_FAILURE =
  "app/Trader/TRADERS_STAFF_FETCH_FAILURE";
