export const CHECK_SUBSCRIPTION_STATUS =
  'app/Subscribe/CHECK_SUBSCRIPTION_STATUS'
export const CHECK_SUBSCRIPTION_STATUS_SUCCESS =
  'app/Subscribe/CHECK_SUBSCRIPTION_STATUS_SUCCESS'
export const CHECK_SUBSCRIPTION_STATUS_FAILURE =
  'app/Subscribe/CHECK_SUBSCRIPTION_STATUS_FAILURE'

export const SUBSCRIBE_USER = 'app/Subscribe/SUBSCRIBE_USER'
export const SUBSCRIBE_USER_SUCCESS = 'app/Subscribe/SUBSCRIBE_USER_SUCCESS'
export const SUBSCRIBE_USER_FAILURE = 'app/Subscribe/SUBSCRIBE_USER_FAILURE'

export const UNSUBSCRIBE_USER = 'app/Subscribe/UNSUBSCRIBE_USER'
export const UNSUBSCRIBE_USER_SUCCESS = 'app/Subscribe/UNSUBSCRIBE_USER_SUCCESS'
export const UNSUBSCRIBE_USER_FAILURE = 'app/Subscribe/UNSUBSCRIBE_USER_FAILURE'
