// VALIDATE CUSTOMER EMAIL
export const VALIDATE_TRADER_CUSTOMER =
  'app/Traders/VALIDATE_TRADER_CUSTOMER_REQUEST'
export const VALIDATE_TRADER_CUSTOMER_SUCCESS =
  'app/Traders/VALIDATE_TRADER_CUSTOMER_SUCCESS'
export const VALIDATE_TRADER_CUSTOMER_FAILURE =
  'app/Traders/VALIDATE_TRADER_CUSTOMER_FAILURE'
export const VALIDATE_TRADER_CUSTOMER_RESET =
  'app/Traders/VALIDATE_TRADER_CUSTOMER_RESET'
// register
export const REGISTER_TRADER = 'app/Traders/REGISTER_TRADER'
export const REGISTER_TRADER_SUCCESS = 'app/Traders/REGISTER_TRADER_SUCCESS'
export const REGISTER_TRADER_FAILURE = 'app/Traders/REGISTER_TRADER_FAILURE'

export const PERSONAL_DETAIL = 'app/Traders/PERSONAL_DETAIL'
export const PERSONAL_DETAIL_SUCCESS = 'app/Traders/PERSONAL_DETAIL_SUCCESS'
export const PERSONAL_DETAIL_FAILURE = 'app/Traders/PERSONAL_DETAIL_FAILURE'

export const GET_POSTCODE = 'app/Traders/GET_POSTCODE'
export const GET_POSTCODE_SUCCESS = 'app/Traders/GET_POSTCODE_SUCCESS'
export const GET_POSTCODE_FAILURE = 'app/Traders/GET_POSTCODE_FAILURE'

export const GET_CATEGORIES = 'app/Traders/GET_CATEGORIES'
export const GET_CATEGORIES_SUCCESS = 'app/Traders/GET_CATEGORIES_SUCCESS'
export const GET_CATEGORIES_FAILURE = 'app/Traders/GET_CATEGORIES_FAILURE'

export const ADD_AREACODE = 'app/Traders/ADD_AREACODE'
export const ADD_AREACODE_SUCCESS = 'app/Traders/ADD_AREACODE_SUCCESS'
export const ADD_AREACODE_FAILURE = 'app/Traders/ADD_AREACODE_FAILURE'

export const ADD_DOCUMENT = 'app/Traders/ADD_DOCUMENT'
export const ADD_DOCUMENT_SUCCESS = 'app/Traders/ADD_DOCUMENT_SUCCESS'
export const ADD_DOCUMENT_FAILURE = 'app/Traders/ADD_DOCUMENT_FAILURE'

export const ADD_SPECIFIC_DOCUMENT = 'app/Traders/ADD_SPECIFIC_DOCUMENT'
export const ADD_SPECIFIC_DOCUMENT_SUCCESS =
  'app/Traders/ADD_SPECIFIC_DOCUMENT_SUCCESS'
export const ADD_SPECIFIC_DOCUMENT_FAILURE =
  'app/Traders/ADD_SPECIFIC_DOCUMENT_FAILURE'

export const GET_DOCUMENTLISTING = 'app/Traders/GET_DOCUMENTLISTING'
export const GET_DOCUMENTLISTING_SUCCESS =
  'app/Traders/GET_DOCUMENTLISTING_SUCCESS'
export const GET_DOCUMENTLISTING_FAILURE =
  'app/Traders/GET_DOCUMENTLISTING_FAILURE'

export const GET_PERSONAL_INFORMATION = 'app/Traders/GET_PERSONAL_INFORMATION'
export const GET_PERSONAL_INFORMATION_SUCCESS =
  'app/Traders/GET_PERSONAL_INFORMATION_SUCCESS'
export const GET_PERSONAL_INFORMATION_FAILURE =
  'app/Traders/GET_PERSONAL_INFORMATION_FAILURE'

export const FETCH_POSTCODE = 'app/Traders/FETCH_POSTCODE'
export const FETCH_POSTCODE_SUCCESS = 'app/Traders/FETCH_POSTCODE_SUCCESS'
export const FETCH_POSTCODE_FAILURE = 'app/Traders/FETCH_POSTCODE_FAILURE'

export const UPDATE_AREACODE = 'app/Traders/UPDATE_AREACODE'
export const UPDATE_AREACODE_SUCCESS = 'app/Traders/UPDATE_AREACODE_SUCCESS'
export const UPDATE_AREACODE_FAILURE = 'app/Traders/UPDATE_AREACODE_FAILURE'

export const CHECK_LOGIN = 'app/Traders/CHECK_LOGIN'
export const CHECK_LOGIN_SUCCESS = 'app/Traders/CHECK_LOGIN_SUCCESS'
export const CHECK_LOGIN_FAILURE = 'app/Traders/CHECK_LOGIN_FAILURE'

export const DISABLE_ADDING = 'app/Traders/DISABLE_ADDING'

export const GET_ALL_DOCUMENT = 'app/Traders/GET_ALL_DOCUMENT'
export const GET_ALL_DOCUMENT_SUCCESS = 'app/Traders/GET_ALL_DOCUMENT_SUCCESS'
export const GET_ALL_DOCUMENT_FAILURE = 'app/Traders/GET_ALL_DOCUMENT_FAILURE'

export const FINISH_SIGNUP = 'app/Traders/FINISH_SIGNUP'
export const FINISH_SIGNUP_SUCCESS = 'app/Traders/FINISH_SIGNUP_SUCCESS'
export const FINISH_SIGNUP_FAILURE = 'app/Traders/FINISH_SIGNUP_FAILURE'

export const GET_TRADER_EMAIL = 'app/Traders/GET_TRADER_EMAIL'
export const GET_TRADER_EMAIL_SUCCESS = 'app/Traders/GET_TRADER_EMAIL_SUCCESS'
export const GET_TRADER_EMAIL_FAILURE = 'app/Traders/GET_TRADER_EMAIL_FAILURE'

export const RESET_PASSWORD = 'app/Traders/RESET_PASSWORD'
export const RESET_PASSWORD_SUCCESS = 'app/Traders/RESET_PASSWORD_SUCCESS'
export const RESET_PASSWORD_FAILURE = 'app/Traders/RESET_PASSWORD_FAILURE'


export const SET_PASSWORD = 'app/Traders/SET_PASSWORD'
export const SET_PASSWORD_SUCCESS = 'app/Traders/SET_PASSWORD_SUCCESS'
export const SET_PASSWORD_FAILURE = 'app/Traders/SET_PASSWORD_FAILURE'
export const RESET_SIGNUP = 'app/Traders/RESET_SIGNUP'
