// VALIDATE CUSTOMER EMAIL
export const VALIDATE_CUSTOMER = 'app/CustomerDetail/VALIDATE_CUSTOMER_REQUEST'
export const VALIDATE_CUSTOMER_SUCCESS =
  'app/CustomerDetail/VALIDATE_CUSTOMER_SUCCESS'
export const VALIDATE_CUSTOMER_FAILURE =
  'app/CustomerDetail/VALIDATE_CUSTOMER_FAILURE'
export const VALIDATE_CUSTOMER_RESET =
  'app/CustomerDetail/VALIDATE_CUSTOMER_RESET'
export const SET_CUSTOMER_VERIFIED = 'app/CustomerDetail/SET_CUSTOMER_VERIFIED'
export const RESET_CUSTOMER_VERIFIED =
  'app/CustomerDetail/RESET_CUSTOMER_VERIFIED'

export const GET_CUSTOMER_ADDRESS = 'app/CustomerDetail/GET_CUSTOMER_ADDRESS'
export const GET_CUSTOMER_ADDRESS_SUCCESS =
  'app/CustomerDetail/GET_CUSTOMER_ADDRESS_SUCCESS'
export const GET_CUSTOMER_ADDRESS_FAILURE =
  'app/CustomerDetail/GET_CUSTOMER_ADDRESS_FAILURE'

export const ADD_CUSTOMER_ADDRESS = 'app/CustomerDetail/ADD_CUSTOMER_ADDRESS'
export const ADD_CUSTOMER_ADDRESS_SUCCESS =
  'app/CustomerDetail/ADD_CUSTOMER_ADDRESS_SUCCESS'
export const ADD_CUSTOMER_ADDRESS_FAILURE =
  'app/CustomerDetail/ADD_CUSTOMER_ADDRESS_FAILURE'

export const EDIT_CUSTOMER_ADDRESS = 'app/CustomerDetail/EDIT_CUSTOMER_ADDRESS'
export const EDIT_CUSTOMER_ADDRESS_SUCCESS =
  'app/CustomerDetail/EDIT_CUSTOMER_ADDRESS_SUCCESS'
export const EDIT_CUSTOMER_ADDRESS_FAILURE =
  'app/CustomerDetail/EDIT_CUSTOMER_ADDRESS_FAILURE'

export const EDIT_CUSTOMER = 'app/CustomerDetail/EDIT_CUSTOMER'
export const EDIT_CUSTOMER_SUCCESS = 'app/CustomerDetail/EDIT_CUSTOMER_SUCCESS'
export const EDIT_CUSTOMER_FAILURE = 'app/CustomerDetail/EDIT_CUSTOMER_FAILURE'

export const VALIDATE_POSTCODE = 'app/CustomerDetail/VALIDATE_POSTCODE'
export const VALIDATE_POSTCODE_SUCCESS =
  'app/CustomerDetail/VALIDATE_POSTCODE_SUCCESS'
export const VALIDATE_POSTCODE_FAILURE =
  'app/CustomerDetail/VALIDATE_POSTCODE_FAILURE'

export const RESEND_VERIFY_MAIL = 'app/CustomerDetail/RESEND_VERIFY_MAIL'
export const RESEND_VERIFY_MAIL_SUCCESS =
  'app/CustomerDetail/RESEND_VERIFY_MAIL_SUCCESS'
export const RESEND_VERIFY_MAIL_FAILURE =
  'app/CustomerDetail/RESEND_VERIFY_MAIL_FAILURE'
